### ISSUE TITLE
[ANDROID] RNCalendarEvents.authorizationStatus returns 'authorised' when permission is not granted 

### ISSUE THREAD

**Issue by Crazy-Ivan** [wmcmahan/react-native-calendar-events#111]
1. Install the app -> 
2. calendar permission is automatically granted  -> 
3. go to the settings -> 
4. switch off calendar permission -> 
5. open the app -> 
6. RNCalendarEvents.authorizationStatus still returns 'authorised'.

**Comment by ivancheng1214** [comment]
Same issue here.
Hope quick response from maintainers...

**Comment by ivancheng1214** [comment]
I did following:
1. install the app
2. restrict calendar access in the pop up modal
3. RNCalendarEvents.authorizationStatus returns authorized in spite of being restricted by user

**Comment by wmcmahan** [comment]
For Androids running API 23 and above, it is necessary to request permission from the user before accessing the Calendar. Prior, these permissions are accessed from [AndroidManifest.xml](https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/AndroidManifest.xml). What is the response from the `authorizeEventStore` call?

**Comment by pepincho** [comment]
Hello guys! @wmcmahan I have the same issue while developing on Android. 
I'm using:
```
compileSdkVersion 27
buildToolsVersion "27.0.3"
``` 
and
```
"react-native-calendar-events": "^1.4.3",
"react-native": "0.52.0",
```
I've already added these lines 
```
<uses-permission android:name="android.permission.WRITE_CALENDAR" />
<uses-permission android:name="android.permission.READ_CALENDAR" />
``` but the response from ```authorizeEventStore``` call is still ```granted``` but there was no dialog to ask user for his permissions.
The other problem that I face is that when I delete an event from the calendar I receive a successful response but the event is still on the user's calendar. I'm not sure what's going on here because on Apple calendar everything is working properly.
Thanks!

**Comment by wmcmahan** [comment]
If the application is not prompting for permission when calling `authorizeEventStore` check your applications `build.gradle` for its targeted SDK. SDKs 23 and higher require the application to ask permission, otherwise its implicitly granted.
