### ISSUE TITLE
How is Event ID defined?

### ISSUE THREAD

**Issue by jeveloper** [wmcmahan/react-native-calendar-events#131]
### Environment
RN 52
react-native-calendar-events 1.5.0

Hey @wmcmahan  Will

Thanks for the great work!

I am trying to figure out a problem.

Your library returns eventID .

however another library that also uses eventKit https://github.com/vonovak/react-native-add-calendar-event returns a list of events for the same date but contains different ID.
I understand that an ID could contain calendarID but in this case they are definitely not the same.

Very strange.

I created the same ticket in that other library.  

Thank you

**Comment by wmcmahan** [comment]
Hey @jeveloper, I believe there might be the differing properties:

`react-native-add-calendar-event` -  appears to be using this [eventIdentifier](https://developer.apple.com/documentation/eventkit/ekevent/1507437-eventidentifier?language=objc)
`react-native-calendar-events` -  is using this [calendarItemIdentifier](https://developer.apple.com/documentation/eventkit/ekcalendaritem/1507075-calendaritemidentifier?language=objc)

These properties should return different UUIDs. Hopefully, this helps.

**Comment by jeveloper** [comment]
Hey Will 

Thanks for response ! This could be good for readme :) 

Wild question, any idea if there is a way to convert one to another . No idea why there would be 2 sets of Identification of a calendar record

**Comment by wmcmahan** [comment]
Thanks @jeveloper! This is making me wonder why `calendarItemIdentifier` was used instead of `eventIdentifier` - it might simply be an artifact from an old use-case.

Unfortunately these properties are from different classes and cannot be converted. The only way (im aware of) is to swap references of `calendarItemIdentifier` with `eventIdentifier`, and `calendarItemWithIdentifier` with `eventWithIdentifier` in the [implementation file](https://github.com/wmcmahan/react-native-calendar-events/blob/master/RNCalendarEvents.m).

I will look into why `eventIdentifier` was not used and check if its not the better option here.

**Comment by jeveloper** [comment]
Appreciate that. 
Thanks for the apple dev references. A little concerning about the fact that the IDs can change , guessing because of iCloud sync work.

**Comment by jeveloper** [comment]
hey Will @wmcmahan  

I'm not too familiar with eventkit sdk. But do you think you might add support for accepting both types of IDs ? Passing an option e.g. { idtype = 'calendarItemIdentifier' }  so that it doesn't break your lib.

I'll propose the same to the other repo owner , i am having a parallel conversation with him :)

**Comment by wmcmahan** [comment]
I think that adding another option might become a little confusing in this case. But in the meantime, I will see about supporting both implicitly.

**Comment by jeveloper** [comment]
Just wanted to let you know that i worked with vonovak yesterday and helped him test changes where 2 sets of IDS are returned for IOS and those 2 fields are just duplicates for android case. It worked well so i am combining your library and his.

**Comment by dbasea** [comment]
Hi there @wmcmahan, I've been implementing some calendar solution using this package.  I would like to understand more about changing event Ids.  When does this happen and is there any way I can keep track of my events after they change?

**Comment by wmcmahan** [comment]
iOS and Android handle ids differently. Currently, the id's used should probably avoid long caching since these id's change depending on external calendar syncing and are not guaranteed to stay the same. This would be a large change to swap id's used, but can address with a next major release.

Closing for now with feature request noted
