### ISSUE TITLE
Undefined is not an Object(RNCalendarEvent.authorizeEventStore)

### ISSUE THREAD

**Issue by StanislavSergeev** [wmcmahan/react-native-calendar-events#139]
I tried to use Authorize to Calendar Event Store

> RNCalendarEvents.authorizeEventStore().then(response => alert(response))

But it doesn't alert any response. only say Undefined is not an Object

**Comment by wmcmahan** [comment]
@StanislavSergeev, this is normally because the package is not [linked](https://github.com/wmcmahan/react-native-calendar-events#getting-started) - for iOS if automatic linking is not working, then you may need to manually link it - [React Native instructions](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking)

**Comment by StanislavSergeev** [comment]
Thanks
