### ISSUE TITLE
Can't read property 'authorizationStatus' of undefined

### ISSUE THREAD

**Issue by bhatti-waqas** [wmcmahan/react-native-calendar-events#149]
I have followed all the instructions given for ios. But when I am trying to use 'RNCalendarEvents.authorizationStatus()' I get following error. 

Can't read property 'authorizationStatus' of undefined

**Comment by wmcmahan** [comment]
Hi @bhatti-waqas, this is usually caused by the library not being properly linked. I would recommend checking the [setup instructions](https://github.com/wmcmahan/react-native-calendar-events#step-2---link-the-library) if anything was missed.

If this error is coming from iOS after running the automatic link command, you may need to try manually linking the library.

**Comment by mikeumus** [comment]
Also check out @3DEsprit's article here:
- https://networksynapse.net/quick-introduction-to-react-natives-calendar-events/
