### ISSUE TITLE
Crash on android with property frequency  in a recurrenceRule

### ISSUE THREAD

**Issue by BruceCode** [wmcmahan/react-native-calendar-events#159]
The app crash when use the property frequency  in the recurrenceRule

react-native-cli: 2.0.1
react-native: 0.47.1

**Comment by wmcmahan** [comment]
Hey @BruceCode, what is the value you are using for `frequency`?

**Comment by BruceCode** [comment]
@wmcmahan 'weekly'

**Comment by sampsasaarela** [comment]
Got it to work. I had to add `duration: null` to the `recurrenceRule`. 

So here it is working params:
```javascript
{ 
  calendarId: '1',
  startDate: '2018-08-17T03:00:00.000Z',
  endDate: '2018-08-17T03:15:00.000Z',
  recurrenceRule: { 
    duration: null,
    frequency: 'daily',
    startDate: '2018-08-17T00:00:00.000Z',
    endDate: '2018-10-14T23:59:59.999Z' 
  },
  alarms: [ { date: 0 } ] 
}
```

It seems that duration parameter is not documented anywhere, but it defaults to [PT1H](https://github.com/wmcmahan/react-native-calendar-events/blob/master/android/src/main/java/com/calendarevents/CalendarEvents.java#L393).

And suggestion in #46 didn't work because if `recurrenceRule` doesn't have frequency it will be ignored and it doesn't respect occurrence rule.

**Comment by BruceCode** [comment]
When adding **duration: null**, it no longer crash.
Thank you.

**Comment by fendermany** [comment]
It doesn't help when I editing existing event
