### ISSUE TITLE
UI gets stuck on calling Alert.alert in .then method of RNCalendarEvents.saveEvent()

### ISSUE THREAD

**Issue by jake41** [wmcmahan/react-native-calendar-events#231]
This is my code for the same: 

```
 RNCalendarEvents.saveEvent("Appointment", {
              startDate: `${sDate}`,
              endDate: `${eDate}`
            })
              .then(res => {
                console.log(
                  `Added appointment to Calendar. \nCalendarEventID: ${res} `
                );
                Alert.alert("Added apppointment to calendar");
              })
              .catch(err =>
                console.log(
                  `Error : ${err} \nError in adding appointment to Calendar`
                )
              );
```

UI becomes unresponsive after the Alert.alert dialog is shown. 

This is working fine in Android. Only in IOS I am facing this issue.

**Comment by ldco2016** [comment]
@jake41 , its not a good sign for me that you have received no response regarding your issue. I have a promise not resolving with `RNCalendarEvents.saveEvent()` as well, which I believe may be due to the fact that I upgraded my app to RN 60.4 from 53.3, my theory is that its related to automatic linking as I am unclear whether I need to run `react-native link` per docs here, or their docs have not been updated for RN 60ish. 

If I go back to a copy of my legacy application and sign in with the same credentials as the upgraded version, I can add to calendar successfully. So I wish someone would help out here, its costing people money.

**Comment by MoOx** [comment]
Please try with 2.0.0 & reopen a new issue if necessary. We improved error handling.
