### ISSUE TITLE
Getting authorization to Calender(question)

### ISSUE THREAD

**Issue by jasan-s** [wmcmahan/react-native-calendar-events#48]
Sorry if this a naive question, First time developing react-native app. In android I would normally declare permission required in manifest,     `<uses-permission android:name="android.permission.READ_CALENDAR" />`, So even with this I would still need to use `authorizeEventStore` to get secondary permission?, or is it only necessary  if the user denied it initially and at run time you want to offer them to change their mind?

**Comment by wmcmahan** [comment]
Hey @jasan-s, since Android Marshmallow, run-time permission requests for "dangerous" permission must be explicitly accepted by the user. [*Source](https://developer.android.com/training/permissions/requesting.html). So I believe its not really a secondary permission, its just a change in how/when user accepts permissions on Android (API 23).
