### ISSUE TITLE
Add demo on README

### ISSUE THREAD

**Issue by lucasbento** [wmcmahan/react-native-calendar-events#59]
A simple gif of the package working would be great.

**Comment by wmcmahan** [comment]
Hi @lucasbento, what would you recommend showing? This is really just an API wrapper and no UI is involved.

**Comment by lucasbento** [comment]
Perhaps adding a `example` folder with a working project and show it working may be a good addition.

**Comment by wmcmahan** [comment]
Ok, thanks for the feedback @lucasbento. I will try put together an example for reference.

**Comment by 3DEsprit** [comment]
I have to agree with this. 

As someone who simply jumped into this functionality with this module as an introduction, the documentation didn't offer much in terms of explanation of use/expectations, and while the examples offered working snippets, someone new wouldn't be able to truly understand since there is little feedback after the methods are run. Overall, it is quite hard to know what to expect as a new user.

I still have to say "thank you very much" for your work, and I understand time doesn't always cater to extra requests like this.

**Comment by blozano824** [comment]
I can't really get this module to work and a working example would be lovely. thanks!

**Comment by 3DEsprit** [comment]
@blozano824 I wrote a [quick article](https://networksynapse.net/quick-introduction-to-react-natives-calendar-events/) for this reason alone. I hope that helps for the time being.

**Comment by wmcmahan** [comment]
Move to list of request #165
